x-netbox: &netbox
  image: docker.io/netboxcommunity/netbox:v4.7.0-5.1.1
  env_file:
    - .env
  environment:
    # NetBox
    ALLOWED_HOSTS: "${NETBOX_ALLOWED_HOSTS}"
    TIME_ZONE: "${NETBOX_TIME_ZONE}"
    SECRET_KEY: "${NETBOX_SECRET_KEY}"
    API_TOKEN_PEPPER_1: "${NETBOX_API_TOKEN_PEPPER_1}"
    CENSUS_REPORTING_ENABLED: "${NETBOX_CENSUS_REPORTING_ENABLED}"
    COPILOT_ENABLED: "${NETBOX_COPILOT_ENABLED}"

    # PostgreSQL
    DB_HOST: "${PSQL_HOST}"
    DB_PORT: "${PSQL_PORT}"
    DB_NAME: "${PSQL_DATABASE}"
    DB_USER: "${PSQL_USERNAME}"
    DB_PASSWORD: "${PSQL_PASSWORD}"
    DB_SSLMODE: "${PSQL_SSL_MODE}"
    DB_CONN_MAX_AGE: "${PSQL_CONN_MAX_AGE}"

    # Redis / Valkey - tasks
    REDIS_HOST: "${REDIS_TASKS_HOST}"
    REDIS_PORT: "${REDIS_TASKS_PORT}"
    REDIS_USERNAME: "${REDIS_TASKS_USERNAME}"
    REDIS_PASSWORD: "${REDIS_TASKS_PASSWORD}"
    REDIS_DATABASE: "${REDIS_TASKS_DATABASE}"
    REDIS_SSL: "${REDIS_TASKS_SSL}"
    REDIS_INSECURE_SKIP_TLS_VERIFY: "${REDIS_TASKS_INSECURE_SKIP_TLS_VERIFY}"

    # Redis / Valkey - cache
    REDIS_CACHE_HOST: "${REDIS_CACHE_HOST}"
    REDIS_CACHE_PORT: "${REDIS_CACHE_PORT}"
    REDIS_CACHE_USERNAME: "${REDIS_CACHE_USERNAME}"
    REDIS_CACHE_PASSWORD: "${REDIS_CACHE_PASSWORD}"
    REDIS_CACHE_DATABASE: "${REDIS_CACHE_DATABASE}"
    REDIS_CACHE_SSL: "${REDIS_CACHE_SSL}"
    REDIS_CACHE_INSECURE_SKIP_TLS_VERIFY: "${REDIS_CACHE_INSECURE_SKIP_TLS_VERIFY}"
