---
services:
  cloudflared:
    image: cloudflare/cloudflared:2026.9.0

    depends_on:
      netbox:
        condition: service_healthy

    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token-file
      - /run/secrets/cloudflare_tunnel_token

    secrets:
      - cloudflare_tunnel_token

    restart: unless-stopped

secrets:
  cloudflare_tunnel_token:
    file: ./secrets/cloudflare_tunnel_token
